### ISSUE TITLE
Unit test: simple search not working

### ISSUE THREAD

**Issue by gregv** [2023-opportunity-hack/syntax-error--DigitalRecordsManagementforMuseumsandHistoricalSites#12]
![image](https://github.com/2023-opportunity-hack/syntax-error--DigitalRecordsManagementforMuseumsandHistoricalSites/assets/6913307/8d55ffaf-1a7d-4652-a45e-cccc0729327e)

Uploaded this zip - unable to find words that I think should exist

![image](https://github.com/2023-opportunity-hack/syntax-error--DigitalRecordsManagementforMuseumsandHistoricalSites/assets/6913307/cddde98f-4137-42e0-9b7e-404fc018aa2b)

![image](https://github.com/2023-opportunity-hack/syntax-error--DigitalRecordsManagementforMuseumsandHistoricalSites/assets/6913307/b6df6339-7434-461d-81da-9aca45173777)

**Comment by loveneetsingh7** [comment]
The search is fully working now
![Screenshot 2024-03-11 at 9 45 20 am](https://github.com/2023-opportunity-hack/syntax-error--DigitalRecordsManagementforMuseumsandHistoricalSites/assets/62647604/9fdd133a-774d-41b3-9386-93942a5aebf7)
