### ISSUE TITLE
Docs: How would the nonprofit use your system?

### ISSUE THREAD

**Issue by gregv** [2023-opportunity-hack/syntax-error--DigitalRecordsManagementforMuseumsandHistoricalSites#14]
Can you walk through an example in GDoc of how the nonprofit would use your system?

Ideally you walk through an example from [section 2 here](https://docs.google.com/document/d/1kqOwkuZZAIePUPsvH6YkLQbFQpEA14E9JVRkMjyZ-Wg/edit#bookmark=id.roi57dv7egi)

**Comment by loveneetsingh7** [comment]
This is the Video example showing how to use the system for searching text
[Preser_Search_Final_demo_1 (1).mov.zip](https://github.com/2023-opportunity-hack/syntax-error--DigitalRecordsManagementforMuseumsandHistoricalSites/files/14561957/Preser_Search_Final_demo_1.1.mov.zip)
