### ISSUE TITLE
File organization does not appear to exist

### ISSUE THREAD

**Issue by gregv** [2023-opportunity-hack/syntax-error--DigitalRecordsManagementforMuseumsandHistoricalSites#15]
See [3. Organize Files](https://docs.google.com/document/d/1kqOwkuZZAIePUPsvH6YkLQbFQpEA14E9JVRkMjyZ-Wg/edit#bookmark=id.odi2whyts5a2)

Is there a way for me to list the files that exist and group them by tags?

I see that I can search by a tag, but how would the nonprofit know what tags exist?

![image](https://github.com/2023-opportunity-hack/syntax-error--DigitalRecordsManagementforMuseumsandHistoricalSites/assets/6913307/85c35589-b99c-4637-bb4a-cdd2b3d32c4c)

**Comment by loveneetsingh7** [comment]
Added View files - to view all files present in the system and Tags section - to view all the tags that have been added. The tags can be edited after searching for a file and clicking on the "edit button" to add or remove any existing tags related to a document
