### ISSUE TITLE
Handle different filetypes 

### ISSUE THREAD

**Issue by gregv** [2023-opportunity-hack/syntax-error--DigitalRecordsManagementforMuseumsandHistoricalSites#5]
The system shall be able to handle uploads from these file types including all of the example files provided [in Google Drive](https://drive.google.com/drive/folders/1YqNogfGPH2t20t92wSaq21DNoOsxTXt4?usp=sharing)
Text
PDFs with text or images or both
Scans of newspapers
Images
Audio files

**Comment by hwelsters** [comment]
The file types above work with the system.
