### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by gregv** [2023-opportunity-hack/syntax-error--DigitalRecordsManagementforMuseumsandHistoricalSites#6]
Search functionality works as described above in #2 of “What we need to build”
https://docs.google.com/document/d/1kqOwkuZZAIePUPsvH6YkLQbFQpEA14E9JVRkMjyZ-Wg/edit#bookmark=id.roi57dv7egi

**Comment by hwelsters** [comment]
Users are able to search for documents using the frontend.
