### ISSUE TITLE
Organization/Grouping/Sorting

### ISSUE THREAD

**Issue by gregv** [2023-opportunity-hack/syntax-error--DigitalRecordsManagementforMuseumsandHistoricalSites#7]
Organization/Grouping/Sorting of files works as described above in #3 “What we need to build”
https://docs.google.com/document/d/1kqOwkuZZAIePUPsvH6YkLQbFQpEA14E9JVRkMjyZ-Wg/edit#bookmark=id.odi2whyts5a2

**Comment by hwelsters** [comment]
Text is automatically extracted from the following file types:
- PDFs with text or images or both (pdf)
- Scans of newspapers (png, jpg, pdf)
- Images (png, jpg)
- Audio files (mp3, mp4)

This text is then searchable using the website.
