### ISSUE TITLE
Docs!

### ISSUE THREAD

**Issue by gregv** [2023-opportunity-hack/syntax-error--DigitalRecordsManagementforMuseumsandHistoricalSites#8]
Documentation on how to deploy the code to a cloud-based system shall be tested via someone not on this team, once you have code and deployment documentation ready, please send us a message in [#npo-preservation-partners-of-the-fox-valley](https://opportunity-hack.slack.com/archives/C05P8SELS0P)

**Comment by hwelsters** [comment]
Completed documentation. It is available in `docs/deployment.md`
